version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DBHOST=db
    ports:
      - '${POSTGRES_PORT}:5432'
  szkolkanodejs:
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=${NODE_ENV}
