version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=szkolka_node_js
    ports:
      - '5431:5432'
  szkolkanodejs:
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
