version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DBHOST=postgres
    ports:
      - '${POSTGRES_PORT}:5432'
  szkolkanodejs:
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - NODE_ENV=${NODE_ENV}
    command: ["npm", "run", "start-docker-dev"]
