version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DBHOST=${POSTGRES_HOST}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - prod-postgres-volume:/var/lib/postgresql/data
  szkolkanodejs:
    depends_on:
      - db
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - PORT=${PORT}
volumes:
  prod-postgres-volume:
