version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DBHOST=db
    ports:
      - '${POSTGRES_PORT}:5432'
  szkolkanodejs:
    depends_on:
      - db
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - PORT=${PORT}
