version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=szkolka_node_js
    ports:
      - '5431:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  szkolkanodejs:
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
      - 9229:9229
    command: ["npm", "run", "start-docker-dev"]

volumes:
  postgres-data: {}
