version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DBHOST=${POSTGRES_HOST}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - dev-postgres-volume:/var/lib/postgresql/data
  szkolkanodejs:
    depends_on:
      - postgres
    image: szkolkanodejs
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder-1
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - POSTGRES_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    command: sh -c './wait-for.sh postgres:5432 -- npm run start-docker-dev'
volumes:
  dev-postgres-volume:
